project:
  type: website

exeucte:
  eval: false

website:
  title: "alephthoughts"
  image: quarto.png
  site-url: "https://alephthoughts.com"
  description: "AI consulting for growing your business"
  page-footer: 
    center:
      - icon: linkedin
        href: https://linkedin.com/in/abhisheksharma-/
      - icon: twitter
        href: https://twitter.com/alephthoughts
      - icon: github
        href: https://github.com/alephthoughts
      - icon: rss
        href: index.xml
  favicon: favicon.ico
  open-graph: true
  twitter-card: 
    creator: "@alephthoughts"
  navbar:
    title: false
    logo: quarto.png
    pinned: true
    right:
      - href: thoughts/
        text: Thoughts
      - href: now.qmd
        text: Now
  google-analytics: "G-E43JZZBJM8"

format:
  html:
    theme: [solar, custom.scss]
    css: 
      - styles.css
    toc: true



